format_version: 3
pipelines:
  helm:
    group: helm
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/nullck/gocd-test
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
      - build:
          elastic_profile_id: helm
          tasks:
            - script: |
                set -e ## avoids that the pipeline is green on failing tests
                echo "bla"
